### ISSUE TITLE
Clevo NP50DB

### ISSUE THREAD

**Issue by harun911** [eebssk1/clevo-insyde-uefi-settings-show-all#1]
Hello there, I stumbled upon this github by accident. I am in the possession of a Clevo NP50DB rebranded as a BTO laptop. The fans are continuously ramping up and down and I feel like the settings might be very aggressive. Ive looked in the bios but could not find any options to change fan speed settings or performance profiles. Do you have these settings available to you when you unlocked your insydeH20 bios? Looking forward to your reply. Thank you.

**Comment by eebssk1** [comment]
> Hello there, I stumbled upon this github by accident. I am in the possession of a Clevo NP50DB rebranded as a BTO laptop. The fans are continuously ramping up and down and I feel like the settings might be very aggressive. Ive looked in the bios but could not find any options to change fan speed settings or performance profiles. Do you have these settings available to you when you unlocked your insydeH20 bios? Looking forward to your reply. Thank you.

Seems no.They are totally controlled by EC.Try upgrade your EC firmware https://repo.palkeo.com/clevo-mirror/ (U/P:repo)

**Comment by eebssk1** [comment]
> > Hello there, I stumbled upon this github by accident. I am in the possession of a Clevo NP50DB rebranded as a BTO laptop. The fans are continuously ramping up and down and I feel like the settings might be very aggressive. Ive looked in the bios but could not find any options to change fan speed settings or performance profiles. Do you have these settings available to you when you unlocked your insydeH20 bios? Looking forward to your reply. Thank you.
> 
> Seems no.They are totally controlled by EC.Try upgrade your EC firmware https://repo.palkeo.com/clevo-mirror/ (U/P:repo)

There is a profile settting controll the offset that the thermal controlll circuit will active,but it seems have no big impact.
