### ISSUE TITLE
NH70RDQ confirmed

### ISSUE THREAD

**Issue by Zuorion** [eebssk1/clevo-insyde-uefi-settings-show-all#2]
Can confirm that  "setup_var 0x133 0x01" did the job on NH70RDQ with Insyde1.07.16
![31 05 2024_PhoneExperienceHost_buXtOcFBFh](https://github.com/eebssk1/clevo-insyde-uefi-settings-show-all/assets/12699159/486aed68-44f9-4a38-af89-3e8e75a7bd5e)

**Comment by eebssk1** [comment]
Thanks. Note updated !

**Comment by Candlemaker44** [comment]
When trying to set 0x133 to 0x01 on NPx0SND-M (Medion Defender p40), I get not allowed to change via efi 0x0000008 - any idea how to get around this?

**Comment by eebssk1** [comment]
> When trying to set 0x133 to 0x01 on NPx0SND-M (Medion Defender p40), I get not allowed to change via efi 0x0000008 - any idea how to get around this?

I suppose NP series are nothing like NH.

**Comment by Candlemaker44** [comment]
So looks like its 0x719, but cant edit it through Ru.EFI or any other way. Need to remove the lock somehow, any ideas?

**Comment by eebssk1** [comment]
> So looks like its 0x719, but cant edit it through Ru.EFI or any other way. Need to remove the lock somehow, any ideas?

"NHxxDPx

    insyde/clevo hard disabled the show all option with a always false compare in their bios.
    You need to unpack the setuputility from the bios then find the assembly and modify it to true and repack_flash the bios to enable the options.
        tested on hasee_z8-cu5xx(mining edtion)
"
Try this maybe?
