### ISSUE TITLE
NH55EJQ (Medion Erazer Crawler E25) working offset

### ISSUE THREAD

**Issue by schnoog** [eebssk1/clevo-insyde-uefi-settings-show-all#3]
Hi, thanks for the information you provide.

I was able to show all setting with the offset

0x212

and value

0x01

which was based on the NHxxExQ-M BIOS 1.07.05RME1 efi extract

0xE3CD2 			Setting: Setup Menu Insyde Full Show, Variable: 0x212 {05 91 10 00 11 00 D1 00 34 12 12 02 10 10 00 01 00}
0xE3CE3 				Option: Hide, Value: 0x0 {09 07 12 00 30 00 00}
0xE3CEA 				Option: Show, Value: 0x1 {09 07 13 00 00 00 01}

**Comment by eebssk1** [comment]
ref: https://github.com/eebssk1/clevo-insyde-uefi-settings-show-all/commit/ed122bc8d99e1103d2974588b2cc95f176362b12

**Comment by eebssk1** [comment]
Thanks for your contribtion !
